;PROGRAM TO find out the largest element in an array of numbers
.MODEL SMALL ;assembler memory model

.STACK 100H

.DATA
MSG1 DB "largest value is $"
ARRAY DW 1234H, 3465H, 7698H, 9798H, 8842H

.CODE

MOV AX,@DATA
MOV DS,AX

MOV SI, OFFSET ARRAY
MOV CX, 5

MOV AX, 0000H
BACK: 
INC SI
INC SI
CMP AX, [SI]
JAE ITER
MOV AX, [SI]
ITER:
LOOP BACK

PUSH AX

MOV DX, OFFSET MSG1
MOV AH, 09H
INT 21H ; INT STANDS FOR INTERRUPT INSTRUCTION 21H IS INTERRUPT NO FOR DOS SERVICES

POP AX
CALL DISPLAY

MOV AH, 4CH
INT 21H

DISPLAY PROC NEAR ; PROC IS KEYWORD FOR PROCEDURE
MOV CH, 04H
MOV CL, 04H
DISP1:
ROL AX, CL ; ROTATE LEFT 4 TIMES
PUSH AX ; SAVING ON STACK
AND AL, 0FH
ADD AL, 30H ; 48 IN DECIMAL
CMP AL, '9' ; COMPARE WITH ASCII VALUE OF 9
JBE DISP2
ADD AL, 7
DISP2: MOV DL, AL
MOV AH, 02H
INT 21H
POP AX
DEC CH
JNZ DISP1
RET
DISPLAY ENDP
END 